-- V129 · Códigos promocionales automáticos con cupos, vigencia y acceso temporal

create table if not exists public.vip_promociones_codigos (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  codigo text not null,
  plan text not null default 'Básico' check (plan in ('Básico','VIP','VIP Pro')),
  duracion_dias integer not null default 7 check (duracion_dias between 1 and 3650),
  cupo_maximo integer null check (cupo_maximo is null or cupo_maximo > 0),
  usos integer not null default 0 check (usos >= 0),
  estado text not null default 'borrador' check (estado in ('borrador','proximamente','activa','pausada','finalizada','oculta')),
  fecha_inicio timestamptz null,
  fecha_fin timestamptz null,
  un_uso_por_whatsapp boolean not null default true,
  solo_nuevos boolean not null default true,
  activacion_automatica boolean not null default true,
  mostrar_boton boolean not null default true,
  origen text not null default '',
  texto_boton text not null default 'Canjear código',
  mensaje_publico text not null default '',
  creado_por uuid null default auth.uid(),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint vip_promociones_fechas_ok check (fecha_fin is null or fecha_inicio is null or fecha_fin > fecha_inicio)
);

create unique index if not exists vip_promociones_codigo_lower_uidx
  on public.vip_promociones_codigos (lower(btrim(codigo)));
create index if not exists vip_promociones_estado_idx
  on public.vip_promociones_codigos (estado, mostrar_boton, fecha_inicio, fecha_fin);

create table if not exists public.vip_promociones_canjes (
  id bigint generated by default as identity primary key,
  promocion_id uuid not null references public.vip_promociones_codigos(id) on delete cascade,
  miembro_id bigint null references public.miembros(id) on delete set null,
  whatsapp text not null,
  whatsapp_normalizado text not null,
  codigo_vip text not null default '',
  plan text not null,
  duracion_dias integer not null,
  estado text not null default 'pendiente' check (estado in ('pendiente','activo','rechazado','cancelado')),
  fecha_inicio date null,
  fecha_vencimiento date null,
  detalle text not null default '',
  creado_en timestamptz not null default now(),
  resuelto_en timestamptz null,
  resuelto_por uuid null
);

create index if not exists vip_promociones_canjes_promo_idx
  on public.vip_promociones_canjes (promocion_id, creado_en desc);
create index if not exists vip_promociones_canjes_wa_idx
  on public.vip_promociones_canjes (whatsapp_normalizado, creado_en desc);

alter table public.vip_promociones_codigos enable row level security;
alter table public.vip_promociones_canjes enable row level security;

revoke all on public.vip_promociones_codigos from anon, authenticated;
revoke all on public.vip_promociones_canjes from anon, authenticated;
revoke all on sequence public.vip_promociones_canjes_id_seq from anon, authenticated;

create or replace function public.vip_promocion_generar_codigo_vip()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_codigo text;
  v_intentos integer := 0;
begin
  loop
    v_intentos := v_intentos + 1;
    v_codigo := 'VIP-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,10));
    exit when not exists(select 1 from public.miembros where upper(codigo_vip)=upper(v_codigo));
    if v_intentos > 20 then
      raise exception 'No fue posible generar un código VIP único';
    end if;
  end loop;
  return v_codigo;
end;
$$;

create or replace function public.vip_promocion_estado_publico()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.vip_promociones_codigos%rowtype;
  v_activa boolean := false;
  v_mensaje text;
begin
  update public.vip_promociones_codigos
     set estado='finalizada', mostrar_boton=false, actualizado_en=now()
   where estado in ('activa','proximamente')
     and (
       (fecha_fin is not null and fecha_fin < now())
       or (cupo_maximo is not null and usos >= cupo_maximo)
     );

  select * into p
  from public.vip_promociones_codigos
  where mostrar_boton=true
    and estado in ('proximamente','activa')
  order by case when estado='activa' then 0 else 1 end, actualizado_en desc
  limit 1;

  if not found then
    return jsonb_build_object('visible',false,'activa',false,'estado','oculta');
  end if;

  v_activa := p.estado='activa'
    and (p.fecha_inicio is null or p.fecha_inicio <= now())
    and (p.fecha_fin is null or p.fecha_fin >= now())
    and (p.cupo_maximo is null or p.usos < p.cupo_maximo);

  v_mensaje := case
    when p.estado='proximamente' then coalesce(nullif(p.mensaje_publico,''),'La promoción estará disponible próximamente.')
    when p.fecha_inicio is not null and p.fecha_inicio > now() then coalesce(nullif(p.mensaje_publico,''),'La promoción todavía no inicia.')
    else coalesce(nullif(p.mensaje_publico,''),'Escribe el código que recibiste para activar tu acceso.')
  end;

  return jsonb_build_object(
    'visible',true,
    'activa',v_activa,
    'estado',case when v_activa then 'activa' else p.estado end,
    'texto_boton',coalesce(nullif(p.texto_boton,''),'Canjear código'),
    'mensaje',v_mensaje,
    'plan',p.plan,
    'duracion_dias',p.duracion_dias,
    'cupos_disponibles',case when p.cupo_maximo is null then null else greatest(p.cupo_maximo-p.usos,0) end
  );
end;
$$;

create or replace function public.vip_promocion_canjear(p_whatsapp text, p_codigo text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.vip_promociones_codigos%rowtype;
  v_wa text;
  v_codigo_vip text;
  v_miembro_id bigint;
  v_canje_id bigint;
  v_inicio date := current_date;
  v_fin date;
  v_nombre text := 'Acceso promocional';
  v_existente boolean;
begin
  v_wa := public.vip_normalizar_whatsapp(p_whatsapp);
  if length(v_wa) < 10 then
    return jsonb_build_object('ok',false,'estado','whatsapp_invalido','mensaje','Escribe un número de WhatsApp válido.');
  end if;
  v_wa := right(v_wa,10);

  if btrim(coalesce(p_codigo,''))='' then
    return jsonb_build_object('ok',false,'estado','codigo_vacio','mensaje','Escribe tu código promocional.');
  end if;

  select * into p
  from public.vip_promociones_codigos
  where lower(btrim(codigo)) = lower(btrim(p_codigo))
  for update;

  if not found then
    return jsonb_build_object('ok',false,'estado','codigo_invalido','mensaje','Código no válido. Revisa que esté escrito exactamente como lo recibiste.');
  end if;

  perform pg_advisory_xact_lock(hashtext(p.id::text || ':' || v_wa));

  if p.estado='proximamente' then
    return jsonb_build_object('ok',false,'estado','proximamente','mensaje',coalesce(nullif(p.mensaje_publico,''),'La promoción todavía no está activa.'));
  end if;
  if p.estado not in ('activa') then
    return jsonb_build_object('ok',false,'estado',p.estado,'mensaje','Este código ya no está disponible.');
  end if;
  if p.fecha_inicio is not null and p.fecha_inicio > now() then
    return jsonb_build_object('ok',false,'estado','no_iniciada','mensaje','La promoción todavía no inicia.');
  end if;
  if p.fecha_fin is not null and p.fecha_fin < now() then
    update public.vip_promociones_codigos set estado='finalizada',mostrar_boton=false,actualizado_en=now() where id=p.id;
    return jsonb_build_object('ok',false,'estado','vencida','mensaje','Esta promoción ya terminó. El código ya no es válido.');
  end if;
  if p.cupo_maximo is not null and p.usos >= p.cupo_maximo then
    update public.vip_promociones_codigos set estado='finalizada',mostrar_boton=false,actualizado_en=now() where id=p.id;
    return jsonb_build_object('ok',false,'estado','sin_cupos','mensaje','Esta promoción ya alcanzó el límite de activaciones. El código ya no es válido.');
  end if;

  if p.un_uso_por_whatsapp and exists(
    select 1 from public.vip_promociones_canjes c
    where c.promocion_id=p.id and c.whatsapp_normalizado=v_wa and c.estado in ('pendiente','activo')
  ) then
    return jsonb_build_object('ok',false,'estado','ya_usado','mensaje','Este número de WhatsApp ya utilizó esta promoción.');
  end if;

  if p.solo_nuevos then
    select exists(
      select 1 from public.miembros m
      where right(public.vip_normalizar_whatsapp(m.whatsapp),10)=v_wa
    ) into v_existente;
    if v_existente then
      return jsonb_build_object('ok',false,'estado','miembro_existente','mensaje','Esta promoción es únicamente para accesos nuevos.');
    end if;
  end if;

  v_fin := v_inicio + p.duracion_dias;

  if not p.activacion_automatica then
    insert into public.vip_promociones_canjes(
      promocion_id,whatsapp,whatsapp_normalizado,plan,duracion_dias,estado,detalle
    ) values(
      p.id,p_whatsapp,v_wa,p.plan,p.duracion_dias,'pendiente','Pendiente de aprobación desde el Centro de Control'
    ) returning id into v_canje_id;

    update public.vip_promociones_codigos
       set usos=usos+1,
           estado=case when cupo_maximo is not null and usos+1>=cupo_maximo then 'finalizada' else estado end,
           mostrar_boton=case when cupo_maximo is not null and usos+1>=cupo_maximo then false else mostrar_boton end,
           actualizado_en=now()
     where id=p.id;

    return jsonb_build_object('ok',true,'estado','pendiente','mensaje','Tu solicitud fue registrada. La administradora revisará la activación.','canje_id',v_canje_id);
  end if;

  v_codigo_vip := public.vip_promocion_generar_codigo_vip();

  insert into public.miembros(nombre,whatsapp,correo,codigo_vip,fecha_inicio,fecha_vencimiento,estado,plan,duracion)
  values(v_nombre,p_whatsapp,null,v_codigo_vip,v_inicio,v_fin,'activo',p.plan,'Prueba '||p.duracion_dias||' días')
  returning id into v_miembro_id;

  insert into public.vip_promociones_canjes(
    promocion_id,miembro_id,whatsapp,whatsapp_normalizado,codigo_vip,plan,duracion_dias,estado,fecha_inicio,fecha_vencimiento,detalle,resuelto_en
  ) values(
    p.id,v_miembro_id,p_whatsapp,v_wa,v_codigo_vip,p.plan,p.duracion_dias,'activo',v_inicio,v_fin,'Activación automática',now()
  ) returning id into v_canje_id;

  update public.vip_promociones_codigos
     set usos=usos+1,
         estado=case when cupo_maximo is not null and usos+1>=cupo_maximo then 'finalizada' else estado end,
         mostrar_boton=case when cupo_maximo is not null and usos+1>=cupo_maximo then false else mostrar_boton end,
         actualizado_en=now()
   where id=p.id;

  return jsonb_build_object(
    'ok',true,
    'estado','activo',
    'mensaje','Tu acceso fue activado correctamente.',
    'codigo_vip',v_codigo_vip,
    'whatsapp',p_whatsapp,
    'plan',p.plan,
    'duracion_dias',p.duracion_dias,
    'fecha_inicio',v_inicio,
    'fecha_vencimiento',v_fin,
    'miembro_id',v_miembro_id,
    'canje_id',v_canje_id
  );
exception when unique_violation then
  return jsonb_build_object('ok',false,'estado','duplicado','mensaje','Este código o WhatsApp ya fue utilizado.');
when others then
  return jsonb_build_object('ok',false,'estado','error','mensaje','No fue posible activar el acceso. Intenta nuevamente.');
end;
$$;

create or replace function public.vip_promocion_admin_listar()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_promos jsonb;
  v_canjes jsonb;
begin
  if not public.vip_tiene_permiso('promociones_editar') then
    raise exception 'Sin permiso';
  end if;

  select coalesce(jsonb_agg(to_jsonb(p) order by p.actualizado_en desc),'[]'::jsonb)
    into v_promos
  from public.vip_promociones_codigos p;

  select coalesce(jsonb_agg(to_jsonb(c) order by c.creado_en desc),'[]'::jsonb)
    into v_canjes
  from (
    select c.id,c.promocion_id,p.nombre as promocion_nombre,c.miembro_id,c.whatsapp,c.codigo_vip,c.plan,c.duracion_dias,c.estado,c.fecha_inicio,c.fecha_vencimiento,c.detalle,c.creado_en,c.resuelto_en
    from public.vip_promociones_canjes c
    join public.vip_promociones_codigos p on p.id=c.promocion_id
    order by c.creado_en desc
    limit 100
  ) c;

  return jsonb_build_object('ok',true,'promociones',v_promos,'canjes',v_canjes);
end;
$$;

create or replace function public.vip_promocion_admin_guardar(p_datos jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_row public.vip_promociones_codigos%rowtype;
  v_cupo integer;
  v_inicio timestamptz;
  v_fin timestamptz;
  v_estado text;
begin
  if not public.vip_tiene_permiso('promociones_editar') then
    return jsonb_build_object('ok',false,'mensaje','No tienes permiso para editar promociones.');
  end if;

  begin v_id := nullif(p_datos->>'id','')::uuid; exception when others then v_id:=null; end;
  begin v_cupo := nullif(p_datos->>'cupo_maximo','')::integer; exception when others then v_cupo:=null; end;
  begin v_inicio := nullif(p_datos->>'fecha_inicio','')::timestamptz; exception when others then v_inicio:=null; end;
  begin v_fin := nullif(p_datos->>'fecha_fin','')::timestamptz; exception when others then v_fin:=null; end;
  v_estado := coalesce(nullif(p_datos->>'estado',''),'borrador');

  if btrim(coalesce(p_datos->>'nombre',''))='' or btrim(coalesce(p_datos->>'codigo',''))='' then
    return jsonb_build_object('ok',false,'mensaje','Escribe el nombre y el código promocional.');
  end if;
  if coalesce((p_datos->>'duracion_dias')::integer,0) < 1 then
    return jsonb_build_object('ok',false,'mensaje','La duración debe ser de al menos un día.');
  end if;
  if v_estado not in ('borrador','proximamente','activa','pausada','finalizada','oculta') then
    return jsonb_build_object('ok',false,'mensaje','Estado no válido.');
  end if;

  if v_id is null then
    insert into public.vip_promociones_codigos(
      nombre,codigo,plan,duracion_dias,cupo_maximo,estado,fecha_inicio,fecha_fin,
      un_uso_por_whatsapp,solo_nuevos,activacion_automatica,mostrar_boton,
      origen,texto_boton,mensaje_publico,creado_por
    ) values(
      btrim(p_datos->>'nombre'),btrim(p_datos->>'codigo'),coalesce(nullif(p_datos->>'plan',''),'Básico'),
      greatest(1,coalesce((p_datos->>'duracion_dias')::integer,7)),v_cupo,v_estado,v_inicio,v_fin,
      coalesce((p_datos->>'un_uso_por_whatsapp')::boolean,true),coalesce((p_datos->>'solo_nuevos')::boolean,true),
      coalesce((p_datos->>'activacion_automatica')::boolean,true),coalesce((p_datos->>'mostrar_boton')::boolean,true),
      coalesce(p_datos->>'origen',''),coalesce(nullif(p_datos->>'texto_boton',''),'Canjear código'),coalesce(p_datos->>'mensaje_publico',''),auth.uid()
    ) returning * into v_row;
  else
    update public.vip_promociones_codigos set
      nombre=btrim(p_datos->>'nombre'),
      codigo=btrim(p_datos->>'codigo'),
      plan=coalesce(nullif(p_datos->>'plan',''),'Básico'),
      duracion_dias=greatest(1,coalesce((p_datos->>'duracion_dias')::integer,7)),
      cupo_maximo=v_cupo,
      estado=v_estado,
      fecha_inicio=v_inicio,
      fecha_fin=v_fin,
      un_uso_por_whatsapp=coalesce((p_datos->>'un_uso_por_whatsapp')::boolean,true),
      solo_nuevos=coalesce((p_datos->>'solo_nuevos')::boolean,true),
      activacion_automatica=coalesce((p_datos->>'activacion_automatica')::boolean,true),
      mostrar_boton=coalesce((p_datos->>'mostrar_boton')::boolean,true),
      origen=coalesce(p_datos->>'origen',''),
      texto_boton=coalesce(nullif(p_datos->>'texto_boton',''),'Canjear código'),
      mensaje_publico=coalesce(p_datos->>'mensaje_publico',''),
      usos=case when coalesce((p_datos->>'reiniciar_usos')::boolean,false) then 0 else usos end,
      actualizado_en=now()
    where id=v_id
    returning * into v_row;
    if not found then return jsonb_build_object('ok',false,'mensaje','No encontramos la promoción.'); end if;
  end if;

  perform public.vip_auditar('promocion_guardar',jsonb_build_object('id',v_row.id,'nombre',v_row.nombre,'estado',v_row.estado));
  return jsonb_build_object('ok',true,'mensaje','Promoción guardada en Supabase.','promocion',to_jsonb(v_row));
exception when unique_violation then
  return jsonb_build_object('ok',false,'mensaje','Ese código promocional ya existe. Usa otro código.');
when check_violation then
  return jsonb_build_object('ok',false,'mensaje','Revisa el plan, duración, cupo y fechas.');
when others then
  return jsonb_build_object('ok',false,'mensaje','No fue posible guardar la promoción.');
end;
$$;

create or replace function public.vip_promocion_admin_estado(p_id uuid, p_estado text, p_mostrar_boton boolean)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_row public.vip_promociones_codigos%rowtype;
begin
  if not public.vip_tiene_permiso('promociones_editar') then return jsonb_build_object('ok',false,'mensaje','Sin permiso.'); end if;
  if p_estado not in ('borrador','proximamente','activa','pausada','finalizada','oculta') then return jsonb_build_object('ok',false,'mensaje','Estado no válido.'); end if;
  update public.vip_promociones_codigos set estado=p_estado,mostrar_boton=coalesce(p_mostrar_boton,mostrar_boton),actualizado_en=now() where id=p_id returning * into v_row;
  if not found then return jsonb_build_object('ok',false,'mensaje','Promoción no encontrada.'); end if;
  perform public.vip_auditar('promocion_estado',jsonb_build_object('id',p_id,'estado',p_estado,'mostrar_boton',p_mostrar_boton));
  return jsonb_build_object('ok',true,'promocion',to_jsonb(v_row));
end;
$$;

create or replace function public.vip_promocion_admin_eliminar(p_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_usos integer;
begin
  if not public.vip_tiene_permiso('promociones_editar') then return jsonb_build_object('ok',false,'mensaje','Sin permiso.'); end if;
  select usos into v_usos from public.vip_promociones_codigos where id=p_id;
  if not found then return jsonb_build_object('ok',false,'mensaje','Promoción no encontrada.'); end if;
  if v_usos>0 then
    update public.vip_promociones_codigos set estado='oculta',mostrar_boton=false,actualizado_en=now() where id=p_id;
    return jsonb_build_object('ok',true,'mensaje','La promoción tiene canjes y se archivó en lugar de eliminarse.');
  end if;
  delete from public.vip_promociones_codigos where id=p_id;
  perform public.vip_auditar('promocion_eliminar',jsonb_build_object('id',p_id));
  return jsonb_build_object('ok',true,'mensaje','Promoción eliminada.');
end;
$$;

create or replace function public.vip_promocion_admin_resolver_canje(p_canje bigint, p_aprobar boolean, p_nombre text default 'Acceso promocional')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  c public.vip_promociones_canjes%rowtype;
  p public.vip_promociones_codigos%rowtype;
  v_codigo text;
  v_miembro bigint;
  v_inicio date:=current_date;
  v_fin date;
begin
  if not public.vip_tiene_permiso('promociones_editar') then return jsonb_build_object('ok',false,'mensaje','Sin permiso.'); end if;
  select * into c from public.vip_promociones_canjes where id=p_canje for update;
  if not found or c.estado<>'pendiente' then return jsonb_build_object('ok',false,'mensaje','La solicitud ya fue resuelta o no existe.'); end if;
  select * into p from public.vip_promociones_codigos where id=c.promocion_id for update;

  if not p_aprobar then
    update public.vip_promociones_canjes set estado='rechazado',detalle='Rechazado por administración',resuelto_en=now(),resuelto_por=auth.uid() where id=c.id;
    update public.vip_promociones_codigos set usos=greatest(usos-1,0),estado=case when estado='finalizada' then 'pausada' else estado end,actualizado_en=now() where id=p.id;
    return jsonb_build_object('ok',true,'mensaje','Solicitud rechazada.');
  end if;

  v_codigo:=public.vip_promocion_generar_codigo_vip(); v_fin:=v_inicio+c.duracion_dias;
  insert into public.miembros(nombre,whatsapp,correo,codigo_vip,fecha_inicio,fecha_vencimiento,estado,plan,duracion)
  values(coalesce(nullif(btrim(p_nombre),''),'Acceso promocional'),c.whatsapp,null,v_codigo,v_inicio,v_fin,'activo',c.plan,'Prueba '||c.duracion_dias||' días')
  returning id into v_miembro;
  update public.vip_promociones_canjes set miembro_id=v_miembro,codigo_vip=v_codigo,estado='activo',fecha_inicio=v_inicio,fecha_vencimiento=v_fin,detalle='Aprobado por administración',resuelto_en=now(),resuelto_por=auth.uid() where id=c.id;
  return jsonb_build_object('ok',true,'mensaje','Acceso aprobado.','codigo_vip',v_codigo,'whatsapp',c.whatsapp,'plan',c.plan,'fecha_vencimiento',v_fin);
end;
$$;

revoke all on function public.vip_promocion_estado_publico() from public;
revoke all on function public.vip_promocion_canjear(text,text) from public;
revoke all on function public.vip_promocion_admin_listar() from public;
revoke all on function public.vip_promocion_admin_guardar(jsonb) from public;
revoke all on function public.vip_promocion_admin_estado(uuid,text,boolean) from public;
revoke all on function public.vip_promocion_admin_eliminar(uuid) from public;
revoke all on function public.vip_promocion_admin_resolver_canje(bigint,boolean,text) from public;

grant execute on function public.vip_promocion_estado_publico() to anon, authenticated;
grant execute on function public.vip_promocion_canjear(text,text) to anon, authenticated;
grant execute on function public.vip_promocion_admin_listar() to authenticated;
grant execute on function public.vip_promocion_admin_guardar(jsonb) to authenticated;
grant execute on function public.vip_promocion_admin_estado(uuid,text,boolean) to authenticated;
grant execute on function public.vip_promocion_admin_eliminar(uuid) to authenticated;
grant execute on function public.vip_promocion_admin_resolver_canje(bigint,boolean,text) to authenticated;

insert into public.vip_promociones_codigos(
  nombre,codigo,plan,duracion_dias,cupo_maximo,estado,un_uso_por_whatsapp,solo_nuevos,
  activacion_automatica,mostrar_boton,origen,texto_boton,mensaje_publico
)
select
  'Lanzamiento Mini Aplicación','MYSUBLID1#Yeah','Básico',7,30,'proximamente',true,true,
  true,true,'Mini aplicación de plantillas','Canjear código',
  'La promoción estará disponible cuando se anuncie la apertura oficial.'
where not exists(
  select 1 from public.vip_promociones_codigos where lower(btrim(codigo))=lower('MYSUBLID1#Yeah')
);
